services:
  db:
    container_name: rip-postgres
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: RIP
    ports:
      - "55632:5432"
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d RIP"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    container_name: rip-adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootroot
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - redis-data:/data

volumes:
  postgresdb-data:
    driver: local
  minio-data:
    driver: local
  redis-data:
    driver: local
